# Generated by Django 4.2.7 on 2024-08-12 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_pedido_fecha_hora_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='conductor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.conductor'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='origen',
            field=models.URLField(null=True),
        ),
    ]
