# Generated by Django 4.2.7 on 2024-10-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='motivo_rechazo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
